version: '3.5'

services:
  discord-ubuntu:
    container_name: leokedin-bot
    build: .
    volumes:
      - .:/home/bot
    ports:
      - "3000:3000"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge